global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'student-task-tracker-metrics'
    metrics_path: /metrics
    static_configs:
    - targets: ['student-task-tracker-metrics:8080']
    
  - job_name: 'task-service'
    metrics_path: /metrics
    static_configs:
    - targets: ['task-service:8080']